# Generated by Django 5.2.15 on 2026-06-27 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver_at', models.DateTimeField(help_text='When this notification should be delivered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailChannel',
            fields=[
                ('tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='notification.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSChannel',
            fields=[
                ('tracking_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('to_phone', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='notification.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
